
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.40.1
      peer-asn: 44444
      my-asn: 44444
    address-pools:
    - name: bgp
      protocol: bgp
      addresses:
      - 192.168.40.5-192.168.40.9
      avoid-buggy-ips: true