apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  rules:
  {{- range $rule := .Values.ingress.rules }}
    - host: {{ $rule.host }}
      http:
        paths:
          - path: {{ $rule.path }}
            backend:
              serviceName: {{ $.Chart.Name }}
              servicePort: {{ $rule.servicePort }}
  {{- end }}