---
- import_playbook: playbooks/deploy_vms.yml
- import_playbook: playbooks/install_base_software.yml
- import_playbook: playbooks/bootstrap_k8s.yml
- import_playbook: playbooks/deploy_metallb.yml
- import_playbook: playbooks/deploy_nginx_ingress.yml