image:
  repository: linuxserver/piwigo
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  strategyType: Recreate
  env:
    - name: PUID
      value: 1001
    - name: PGID
      value: 1001
    - name: TZ
      value: America/Chicago

  ports:
    - name: "http"
      containerPort: 80
      protocol: TCP

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

mounts:
  - name: photos
    mountPath: /config
    nfsserver: 192.168.1.240
    nfspath: /rpool/media/Photos
    readOnly: "false"

service:
  ports:
    - name: http-port
      protocol: TCP
      targetPort: 80
      port: 80

ingress:
  rules:
    - name: webui
      host: piwigo.192.168.40.12.nip.io
      path: /
      servicePort: 80