image:
  repository: sgtsquiggs/deluge-openvpn
  tag: latest
  pullPolicy: IfNotPresent

dnsPolicy: "None"

dnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

env:
  - name: OPENVPN_PROVIDER
    value: "NORDVPN" 
  - name: OPENVPN_USERNAME
    valueFrom:
      secretKeyRef:
        name: "openvpn"
        key: "username"
  - name: OPENVPN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "openvpn"
        key: "password"
  - name: LOCAL_NETWORK
    value: "172.16.0.0/16"
  - name: PUID
    value: "1001"
  - name: PGID
    value: "1001"

volumes:
  - name: "downloads"
    nfs:
      server: 192.168.1.240
      path: "/rpool/transfer/deluge"
      readOnly: false
  - name: "configfolder"
    nfs:
      server: 192.168.1.240
      path: "/rpool/config/deluge"
      readOnly: false
  - name: "dev-tun"
    hostPath:
      path: "/dev/net/tun"

volumeMounts:
  - name: "configfolder"
    mountPath: "/config"
  - name: "downloads"
    mountPath: "/downloads"
  - name: "dev-tun"
    mountPath: "/dev/net/tun"

# Security context for container
securityContext:
  capabilities:
    add:
      - NET_ADMIN

service:
  port: 80

ingress:
  name: webui
  host: deluge.server.lemira
  path: /
  servicePort: 80