image:
  repository: linuxserver/musicbrainz
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  strategyType: Recreate
  env:
    - name: PUID
      value: 1001
    - name: PGID
      value: 1001
    - name: TZ
      value: America/Chicago
    - name: BRAINZCODE
      value: NJ7D3dxH3PlXrsChrT82zIdWBTNqUAljTNakV5m2
    - name: WEBADDRESS
      value: musicbrainz.192.168.40.12.nip.io

  ports:
    - name: "http"
      containerPort: 7878
      protocol: TCP

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

mounts:
  - name: config
    mountPath: /config
    nfsserver: 192.168.1.240
    nfspath: /rpool/config/musicbrainz/config
    readOnly: "false"
  - name: data
    mountPath: /data
    nfsserver: 192.168.1.240
    nfspath: "/rpool/config/musicbrainz/data"
    readOnly: "false"

service:
  ports:
    - name: http-port
      protocol: TCP
      targetPort: 5000
      port: 80

ingress:
  rules:
    - name: webui
      host: musicbrainz.192.168.40.12.nip.io
      path: /
      servicePort: 80