apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-media-books
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 200Gi
    storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-config-calibre
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
    storageClassName: ""