image:
  repository: linuxserver/nzbget
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  strategyType: Recreate
  env:
    - name: PUID
      value: 1001
    - name: PGID
      value: 1001
    - name: TZ
      value: America/Chicago

  ports:
    - name: "http"
      containerPort: 6789
      protocol: TCP

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

mounts:
  - name: config
    mountPath: /config
    nfsserver: 192.168.1.240
    nfspath: /rpool/config/nzbget
    readOnly: false
  - name: downloads
    mountPath: /downloads
    nfsserver: 192.168.1.240
    nfspath: "/rpool/transfer/nzbget"
    readOnly: "false"

service:
  ports:
    - name: http-port
      protocol: TCP
      targetPort: 6789
      port: 80

ingress:
  rules:
    - name: webui
      host: nzbget.192.168.40.12.nip.io
      path: /
      servicePort: 80