---
- hosts: k8s_master:k8s_nodes
  gather_facts: False
  vars:
    CNI_VERSION: "v0.8.2"
    CRICTL_VERSION: "v1.17.0"
    KUBE_VERSION
  tasks:
    - name: Create CNI folder
      file:
        path: /opt/cni/bin
        state: directory
        mode: '0777'

    - name: Download CNI plugins
      get_url:
        url: "https://github.com/containernetworking/plugins/releases/download/{{ CNI_VERSION }}/cni-plugins-linux-amd64-{{ CNI_VERSION }}.tgz"
        dest: /tmp/cni_plugins.tgz

    - name: Extract CNI plugins to CNI folder
      unarchive:
        src: /tmp/cni_plugins.tgz
        dest: /opt/cni/bin

    - name: Create command directory
      file:
        path: /usr/local/bin
        state: directory
        mode: '0777'

    - name: Download crictl
      get_url:
        url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ CRICTL_VERSION }}/crictl-{{ CRICTL_VERSION }}-linux-amd64.tar.gz"
        dest: /tmp/crictl.tar.gz

    - name: Extract crictl to command directory
      unarchive:
        src: /tmp/crictl.tar.gz
        dest: /usr/local/bin
    
