image:
  repository: linuxserver/mariadb
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  strategyType: Recreate
  env:
    - name: PUID
      value: 1001
    - name: PGID
      value: 1001
    - name: TZ
      value: America/Chicago
    - name: MYSQL_DATABASE
      value: piwigo
    - name: MYSQL_USER
      value: piwigo_user
    - name: MYSQL_PASSWORD
      value: piwigo_pwd

  ports:
    - name: "http"
      containerPort: 3306
      protocol: TCP

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

mounts:
  - name: config
    mountPath: /config
    nfsserver: 192.168.1.240
    nfspath: /rpool/config/piwigo
    readOnly: "false"

service:
  ports:
    - name: http-port
      protocol: TCP
      targetPort: 3306
      port: 3306