apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8112
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
