apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-books
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /rpool/media/Books
    server: 192.168.40.240
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-media-booksbase
# spec:
#   capacity:
#     storage: 200Gi
#   accessModes:
#     - ReadWriteOnce
#   nfs:
#     path: /rpool/media/BooksBase
#     server: 192.168.40.240
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-config-calibre-web
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /rpool/config/calibre-web
    server: 192.168.40.240
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-config-grocy
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /rpool/config/grocy
    server: 192.168.40.240