image:
  repository: linuxserver/jackett
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  strategyType: Recreate
  env:
    - name: PUID
      value: 1001
    - name: PGID
      value: 1001
    - name: TZ
      value: America/Chicago
    - name: AUTO_UPDATE
      value: "true"

  ports:
    - name: "http"
      containerPort: 9117
      protocol: TCP

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

mounts:
  - name: config
    mountPath: /config
    nfsserver: 192.168.1.240
    nfspath: /rpool/config/jackett
    readOnly: "false"
  - name: torrent-blackhole
    mountPath: /downloads
    nfsserver: 192.168.1.240
    nfspath: "/rpool/transfer/blackhole"
    readOnly: "false"

service:
  ports:
    - name: http-port
      protocol: TCP
      targetPort: 9117
      port: 80

ingress:
  rules:
    - name: webui
      host: jackett.server.lemira
      path: /
      servicePort: 80